name: PR Test

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  test-init-command:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Test setup command availability
      run: |
        # Test that setup command is available in help
        if node dist/cli/brain.js --help | grep -q "setup.*Interactive setup"; then
          echo "✅ Setup command found in help"
        else
          echo "❌ Setup command not found in help"
          exit 1
        fi
    
    - name: Test package installation flow
      run: |
        # Create test environment
        mkdir -p test-env
        cd test-env
        
        # Pack the current version
        npm pack ../
        
        # Test installation
        npm init -y
        npm install brain-*.tgz
        
        # Verify brain command is available
        if npx brain --help | grep -q "setup.*Interactive setup"; then
          echo "✅ Package installs correctly with setup command"
        else
          echo "❌ Package installation failed or setup command missing"
          exit 1
        fi
        
        # Test basic commands work
        npx brain --version
        npx brain status || echo "Expected to fail without setup"
        
        echo "✅ All installation tests passed"

  compatibility-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Test basic functionality
      run: |
        node dist/cli/brain.js --version
        node dist/cli/brain.js --help
      shell: bash
    
    - name: Test with test notes
      run: |
        # Test with included test notes
        node dist/cli/brain.js status || echo "Expected to fail without setup"
      shell: bash